plugins { id 'com.android.application' }
android {
    namespace 'com.najmspace.app'
    compileSdk 35
    defaultConfig {
        applicationId 'com.najmspace.app'
        minSdk 19
        targetSdk 28
        versionCode 31
        versionName '3.1'
    }
}
dependencies {
    implementation project(':droidplugin')
}
