plugins { id 'com.android.application' }
android {
    namespace 'com.najmspace.app'
    compileSdk 35
    defaultConfig {
        applicationId 'com.najmspace.app'
        minSdk 19
        targetSdk 28
        versionCode 30
        versionName '3.0'
    }
}
dependencies {
    implementation project(':droidplugin')
}
